name = "demo-cse-summarize"
python_application = "app:app"
healthcheck_endpoint = "/health"
tests_cmd = "pytest"
tests_requirements = [
    "intel-sgx-ra",
    "pytest==7.2.0",
]

[cloud]
project = "default"
hardware = "8g-eu-001"
code = "mse_src"
tests = "tests"
docker = "ghcr.io/cosmian/mse-kms-client:20231107093829"
secrets="secrets.json"