---
name: Build, test and release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install flake8 build
      - name: Linter
        run: |
          cd app/
          flake8 --max-line-length=100 --ignore E501,E203
      - name: Build package
        run: |
          cd app/
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: cosmian-ai-runner
          path: ./app/dist
          retention-days: 10

  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12.5
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cosmian-ai-runner
          path: ./dist
      - name: Install dependencies
        run: |
          pip install dist/*.whl

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cosmian-ai-runner
          path: ./dist
      - name: Release on tags, attach asset on release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*

  push:
    needs: build
    name: package.cosmian.com
    runs-on: [self-hosted, no-tee]
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cosmian-ai-runner
          path: ./dist

      - name: Push latest build to package.cosmian.com
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian-ai-runner/last_build
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp ./dist/cosmian_ai_runner-* cosmian@package.cosmian.com:$DESTINATION_DIR/

      - name: Push version tag to package.cosmian.com
        if: startsWith(github.ref, 'refs/tags/')
        env:
          VERSION: ${{ github.ref_name }}
        run: |
          set -x
          DESTINATION_DIR=/mnt/package/cosmian-ai-runner/$VERSION
          ssh cosmian@package.cosmian.com mkdir -p $DESTINATION_DIR
          scp ./dist/cosmian_ai_runner-* cosmian@package.cosmian.com:$DESTINATION_DIR/
