---
  name: Build, test and release

  on: [push]

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-python@v3
            with:
              python-version: 3.9
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install flake8 build
          - name: Linter
            run: |
                cd app/
                flake8 --max-line-length=100 --ignore E501,E203
          - name: Build package
            run: |
                cd app/
                python -m build
          - uses: actions/upload-artifact@v3.1.3
            with:
              name: cosmian_ai_backend_dist
              path: ./app/dist
              retention-days: 10

    release:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Download artifact
          uses: actions/download-artifact@v3.0.2
          with:
            name: cosmian_ai_backend_dist
            path: ./dist
        - name: Release on tags, attach asset on release
          if: startsWith(github.ref, 'refs/tags/')
          uses: softprops/action-gh-release@v1
          with:
            files: dist/*
